import { normalizeText } from "./calculations.js";

export const LANGUAGE_ALIASES = new Map([
  ["arab", "Arabic"],
  ["arabic", "Arabic"],
  ["ar", "Arabic"],
  ["arabisch", "Arabic"],
  ["arapca", "Arabic"],
  ["arabe", "Arabic"],
  ["bangla", "Bengali"],
  ["bengali", "Bengali"],
  ["bengal", "Bengali"],
  ["burmese", "Burmese"],
  ["myanmar", "Burmese"],
  ["cantonese", "Chinese"],
  ["chinese", "Chinese"],
  ["mandarin", "Chinese"],
  ["zh", "Chinese"],
  ["cince", "Chinese"],
  ["chinesisch", "Chinese"],
  ["czech", "Czech"],
  ["danish", "Danish"],
  ["dutch", "Dutch"],
  ["english", "English"],
  ["eng", "English"],
  ["en", "English"],
  ["englisch", "English"],
  ["ingles", "English"],
  ["anglais", "English"],
  ["ingilizce", "English"],
  ["inglizce", "English"],
  ["filipino", "Filipino"],
  ["tagalog", "Filipino"],
  ["finnish", "Finnish"],
  ["french", "French"],
  ["fr", "French"],
  ["fra", "French"],
  ["fre", "French"],
  ["francais", "French"],
  ["français", "French"],
  ["franzosisch", "French"],
  ["fransizca", "French"],
  ["german", "German"],
  ["de", "German"],
  ["ger", "German"],
  ["deu", "German"],
  ["deutsch", "German"],
  ["allemand", "German"],
  ["almanca", "German"],
  ["greek", "Greek"],
  ["hausa", "Hausa"],
  ["hebrew", "Hebrew"],
  ["hindi", "Hindi"],
  ["indian", "Hindi"],
  ["hungarian", "Hungarian"],
  ["igbo", "Igbo"],
  ["indonesian", "Indonesian"],
  ["indonesia", "Indonesian"],
  ["bahasa", "Indonesian"],
  ["bahasa indonesia", "Indonesian"],
  ["italian", "Italian"],
  ["italiano", "Italian"],
  ["italienisch", "Italian"],
  ["italyanca", "Italian"],
  ["it", "Italian"],
  ["ita", "Italian"],
  ["japanese", "Japanese"],
  ["jp", "Japanese"],
  ["khmer", "Khmer"],
  ["cambodian", "Khmer"],
  ["korean", "Korean"],
  ["kr", "Korean"],
  ["lao", "Lao"],
  ["luganda", "Luganda"],
  ["malay", "Malay"],
  ["malaysia", "Malay"],
  ["bahasa malaysia", "Malay"],
  ["nepali", "Nepali"],
  ["norwegian", "Norwegian"],
  ["polish", "Polish"],
  ["portuguese", "Portuguese"],
  ["pt", "Portuguese"],
  ["por", "Portuguese"],
  ["portugues", "Portuguese"],
  ["portugiesisch", "Portuguese"],
  ["portekizce", "Portuguese"],
  ["romanian", "Romanian"],
  ["russian", "Russian"],
  ["ru", "Russian"],
  ["russisch", "Russian"],
  ["rusca", "Russian"],
  ["shona", "Shona"],
  ["sinhala", "Sinhala"],
  ["sinhalese", "Sinhala"],
  ["spanish", "Spanish"],
  ["es", "Spanish"],
  ["spa", "Spanish"],
  ["espanol", "Spanish"],
  ["español", "Spanish"],
  ["spanisch", "Spanish"],
  ["ispanyolca", "Spanish"],
  ["castellano", "Spanish"],
  ["swahili", "Swahili"],
  ["swedish", "Swedish"],
  ["tamil", "Tamil"],
  ["thai", "Thai"],
  ["twi", "Twi"],
  ["thailand", "Thai"],
  ["turkish", "Turkish"],
  ["turkce", "Turkish"],
  ["turkey", "Turkish"],
  ["ukrainian", "Ukrainian"],
  ["urdu", "Urdu"],
  ["vietnamese", "Vietnamese"],
  ["viet", "Vietnamese"],
  ["xhosa", "Xhosa"],
  ["yoruba", "Yoruba"],
  ["zulu", "Zulu"],
]);

const COUNTRY_LANGUAGE_ENTRIES = [
  ["Afghanistan", ["Dari", "Pashto"]],
  ["Albania", ["Albanian"]],
  ["Algeria", ["Arabic", "French"]],
  ["Angola", ["Portuguese"]],
  ["Argentina", ["Spanish"]],
  ["Armenia", ["Armenian"]],
  ["Australia", []],
  ["Austria", ["German"]],
  ["Azerbaijan", ["Azerbaijani"]],
  ["Bahrain", ["Arabic"]],
  ["Bangladesh", ["Bengali"]],
  ["Belarus", ["Belarusian", "Russian"]],
  ["Belgium", ["Dutch", "French"]],
  ["Bolivia", ["Spanish"]],
  ["Bosnia And Herzegovina", ["Bosnian"]],
  ["Brazil", ["Portuguese"]],
  ["Bulgaria", ["Bulgarian"]],
  ["Cambodia", ["Khmer"]],
  ["Cameroon", ["French"]],
  ["Canada", ["French"]],
  ["Chile", ["Spanish"]],
  ["China", ["Chinese"]],
  ["Colombia", ["Spanish"]],
  ["Costa Rica", ["Spanish"]],
  ["Cote D'Ivoire", ["French"]],
  ["Croatia", ["Croatian"]],
  ["Cuba", ["Spanish"]],
  ["Cyprus", ["Greek", "Turkish"]],
  ["Czech Republic", ["Czech"]],
  ["Czechia", ["Czech"]],
  ["Denmark", ["Danish"]],
  ["Dominican Republic", ["Spanish"]],
  ["Ecuador", ["Spanish"]],
  ["Egypt", ["Arabic"]],
  ["El Salvador", ["Spanish"]],
  ["Estonia", ["Estonian"]],
  ["Ethiopia", ["Amharic"]],
  ["Finland", ["Finnish"]],
  ["France", ["French"]],
  ["French Guiana", ["French"]],
  ["Georgia", ["Georgian"]],
  ["Germany", ["German"]],
  ["Ghana", ["Twi"]],
  ["Greece", ["Greek"]],
  ["Grenada", []],
  ["Guatemala", ["Spanish"]],
  ["Honduras", ["Spanish"]],
  ["Hong Kong", ["Chinese"]],
  ["Hungary", ["Hungarian"]],
  ["Iceland", ["Icelandic"]],
  ["India", ["Hindi", "Urdu"]],
  ["Indonesia", ["Indonesian"]],
  ["Iran", ["Persian"]],
  ["Iraq", ["Arabic"]],
  ["Ireland", []],
  ["Israel", ["Hebrew"]],
  ["Italy", ["Italian"]],
  ["Jamaica", []],
  ["Japan", ["Japanese"]],
  ["Jordan", ["Arabic"]],
  ["Kazakhstan", ["Kazakh", "Russian"]],
  ["Kenya", ["Swahili"]],
  ["Kuwait", ["Arabic"]],
  ["Laos", ["Lao"]],
  ["Latvia", ["Latvian"]],
  ["Lebanon", ["Arabic"]],
  ["Libya", ["Arabic"]],
  ["Lithuania", ["Lithuanian"]],
  ["Luxembourg", ["French", "German"]],
  ["Macau", ["Chinese"]],
  ["Madagascar", ["French"]],
  ["Malaysia", ["Malay"]],
  ["Maldives", ["Dhivehi"]],
  ["Malta", ["Maltese"]],
  ["Martinique", ["French"]],
  ["Guadeloupe", ["French"]],
  ["Reunion", ["French"]],
  ["Mexico", ["Spanish"]],
  ["Moldova", ["Romanian"]],
  ["Mongolia", ["Mongolian"]],
  ["Morocco", ["Arabic", "French"]],
  ["Myanmar", ["Burmese"]],
  ["Nepal", ["Nepali"]],
  ["Netherlands", ["Dutch"]],
  ["New Caledonia", ["French"]],
  ["New Zealand", []],
  ["Nicaragua", ["Spanish"]],
  ["Nigeria", ["Hausa", "Yoruba", "Igbo"]],
  ["Norway", ["Norwegian"]],
  ["Oman", ["Arabic"]],
  ["Pakistan", ["Urdu"]],
  ["Palestine", ["Arabic"]],
  ["Panama", ["Spanish"]],
  ["Paraguay", ["Spanish"]],
  ["Peru", ["Spanish"]],
  ["Philippines", ["Filipino"]],
  ["Poland", ["Polish"]],
  ["Portugal", ["Portuguese"]],
  ["Puerto Rico", ["Spanish"]],
  ["Qatar", ["Arabic"]],
  ["Romania", ["Romanian"]],
  ["Russia", ["Russian"]],
  ["Rwanda", ["Kinyarwanda", "French"]],
  ["Saudi Arabia", ["Arabic"]],
  ["Senegal", ["French"]],
  ["Serbia", ["Serbian"]],
  ["Singapore", ["Malay", "Chinese"]],
  ["Slovakia", ["Slovak"]],
  ["Slovenia", ["Slovenian"]],
  ["South Africa", ["Afrikaans", "Zulu", "Xhosa"]],
  ["South Korea", ["Korean"]],
  ["Spain", ["Spanish"]],
  ["Sri Lanka", ["Sinhala", "Tamil"]],
  ["Sudan", ["Arabic"]],
  ["Sweden", ["Swedish"]],
  ["Switzerland", ["German", "French", "Italian"]],
  ["Syria", ["Arabic"]],
  ["Taiwan", ["Chinese"]],
  ["Tanzania", ["Swahili"]],
  ["Thailand", ["Thai"]],
  ["Tunisia", ["Arabic", "French"]],
  ["Turkey", ["Turkish"]],
  ["Turkiye", ["Turkish"]],
  ["Uganda", ["Swahili", "Luganda"]],
  ["Ukraine", ["Ukrainian"]],
  ["United Arab Emirates", ["Arabic"]],
  ["United Kingdom", []],
  ["United States", []],
  ["Uruguay", ["Spanish"]],
  ["Uzbekistan", ["Uzbek"]],
  ["Venezuela", ["Spanish"]],
  ["Vietnam", ["Vietnamese"]],
  ["Yemen", ["Arabic"]],
  ["Zambia", ["Bemba"]],
  ["Zimbabwe", ["Shona"]],
];

export const COUNTRY_ALIASES = new Map([
  ["ae", "United Arab Emirates"],
  ["uae", "United Arab Emirates"],
  ["emirates", "United Arab Emirates"],
  ["dubai", "United Arab Emirates"],
  ["uk", "United Kingdom"],
  ["gb", "United Kingdom"],
  ["great britain", "United Kingdom"],
  ["usa", "United States"],
  ["us", "United States"],
  ["cote divoire", "Cote D'Ivoire"],
  ["ivory coast", "Cote D'Ivoire"],
  ["south korea", "South Korea"],
  ["korea", "South Korea"],
  ["hongkong", "Hong Kong"],
  ["hk", "Hong Kong"],
  ["macao", "Macau"],
  ["macau", "Macau"],
  ["reunion", "Reunion"],
  ["la reunion", "Reunion"],
  ["czech republic", "Czechia"],
  ["dr congo", "Congo"],
  ["congo", "Congo"],
  ["russia", "Russia"],
  ["turkey", "Turkiye"],
  ["switzerland", "Switzerland"],
  ["swiss", "Switzerland"],
  ["schweiz", "Switzerland"],
  ["suisse", "Switzerland"],
  ["ch", "Switzerland"],
  ["che", "Switzerland"],
  ["french guiana", "French Guiana"],
  ["guyane", "French Guiana"],
  ["gf", "French Guiana"],
]);

function titleCase(value = "") {
  return String(value || "")
    .trim()
    .toLocaleLowerCase("en-US")
    .replace(/\b[a-z]/g, (char) => char.toUpperCase());
}

function buildNativeLanguageMap() {
  const output = new Map();
  for (const [country, languages] of COUNTRY_LANGUAGE_ENTRIES) {
    output.set(normalizeText(country), languages);
  }
  for (const [alias, canonical] of COUNTRY_ALIASES.entries()) {
    const languages = output.get(normalizeText(canonical));
    if (languages) {
      output.set(alias, languages);
    }
  }
  return output;
}

export const NATIVE_LANGUAGES_BY_COUNTRY = buildNativeLanguageMap();

function compactCountryToken(value = "") {
  return String(value || "")
    .replace(/[.\-'/]/g, "")
    .replace(/\s+/g, "");
}

export function normalizeKycCountry(value = "") {
  const raw = String(value || "").trim();
  if (!raw) {
    return "Unknown";
  }
  const normalized = normalizeText(raw);
  const alias =
    COUNTRY_ALIASES.get(normalized) ||
    COUNTRY_ALIASES.get(compactCountryToken(normalized));
  if (alias) {
    return titleCase(alias);
  }
  return titleCase(raw) || "Unknown";
}

export function nativeLanguagesForCountry(country = "") {
  const normalizedCountry = normalizeText(normalizeKycCountry(country));
  return NATIVE_LANGUAGES_BY_COUNTRY.get(normalizedCountry) || [];
}

export function isNativeLanguageForCountry(language = "", country = "") {
  const nativeLanguages = nativeLanguagesForCountry(country);
  const normalizedLanguage = normalizeText(language);
  return nativeLanguages.some((item) => normalizeText(item) === normalizedLanguage);
}
